---
- name: configure HAproxy
  hosts: load_balancer
  become: true
  tasks:
    - name: configure HAproxy settings
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:  restart haproxy

    - name: Enable and start HAproxy
      service:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted    
